### ISSUE TITLE
Adding a function to submit answers

### ISSUE THREAD

**Issue by foxzsz** [JustTalDevelops/go-hcaptcha#12]
Currently the Solve function is used to get and submit the answers using the implemented solver. However a better solution would be to make a function which uses the answers as a argument. This would allow for easier integration with custom solvers and would still work perfectly fine with YOLOv3.

Example of how it could look like:
`solved, err := c.Submit_Guess(answers)`

**Comment by JustTalDevelops** [comment]
I guess I just don't really understand how this would make implementing custom solvers easier. The current system is essentially the same, however instead of submitting answers, you call `Solve` on a Solver structure which solves for you. You can access the token right after that with `c.Token()`. There's not much of a difference and I don't really see how changing this would have much of an effect, unless you'd like to elaborate?

**Comment by JustTalDevelops** [comment]
If you would like to make this change yourself, you're free to open a PR, but personally I don't see a point in changing this myself if I don't see a place that it would actually be useful.

**Comment by foxzsz** [comment]
My bad, I thought the solver structure was embedded in the module and couldn't be changed. However I will still open a PR including this change, because I think it would be simpler to just have a function to submit answers instead of creating a structure for it. But that's just my opinion

**Comment by JustTalDevelops** [comment]
Oh, no problem. I should probably improve the documentation, lol. Feel free to open one!
