### ISSUE TITLE
[Q] What happened to YOLO ?

### ISSUE THREAD

**Issue by chris-aeviator** [JustTalDevelops/go-hcaptcha#22]
Hi - `go-hcaptcha` has shown impressive performance (<10sec) for me with integrating YOLO as the solver. I can see in the readme now that the `YOLOsolver` has been replaced by `GuessSolver` while your commit msg seems to indicate we can now use multiple solvers. Has YOLO been removed?

**Comment by JustTalDevelops** [comment]
Hi Chris!

`YOLOSolver` works tremendously well on many systems, however after careful consideration, I decided to remove it from go-hcaptcha. The main reason for this is because the implementation that go-hcaptcha used relied on CGO along with a requirement of the YOLOv3 configuration files, even if you were not planning on utilizing YOLO.

I think a better approach is to implement an example solver, AKA `GuessSolver` into the library to show how custom solvers can be implemented and allow these solvers to be implemented outside the library, as they can be done so fairly trivially. This allows any user to implement solving capabilities however or with whatever APIs or algorithms they'd like.

I hope that clears up any questions - feel free to reopen this issue if you have any more.
Tal

**Comment by chris-aeviator** [comment]
thanks tal for the clear explaination - reverting back in my code to the hcaptcha solver is not prohibited by anything according to that then right?

EDIT:
re-reading your text I see that I'm able to implement any kind of solver \O/

**Comment by JustTalDevelops** [comment]
Yep, you should be able to utilize any solver or image recognition API by satisfying the Solver interface.
